# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

# CONFIG_SENSOR=y
CONFIG_BLINK=y
CONFIG_GPIO=y
# CONFIG_PM=y
# CONFIG_PM_DEVICE=y
# CONFIG_PM_DEVICE_RUNTIME=y
# CONFIG_PM_DEVICE_SYSTEM_MANAGED=y

# Power Management
CONFIG_PM=y
CONFIG_PM_DEVICE=y

# Disable Serial/UART for lowest idle current (typically < 10µA)
CONFIG_SERIAL=n

# Disable unnecessary logging
CONFIG_LOG=n